FROM golang:1.24.9-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY ./ ./

# RUN apt-get update
# RUN apt-get -y install postgresql-client

# RUN apt-get install dos2unix

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cchat-server-app ./cmd/cchat/main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache postgresql-client

COPY --from=builder /src/cchat-server-app .
COPY --from=builder /src/.env .
COPY --from=builder /src/config/local.yaml .

CMD ["./cchat-server-app"]







# 



# WORKDIR /app

# RUN apk add --no-cache postgresql-client

# COPY --from=builder /src/bank .

# EXPOSE 3030

# CMD ["./bank"]